egg: Fix use of libgcrypt GCRY_THREAD_OPTION_PTHREAD_IMPL
On certain libgcrypt versions (like 1.5.0) we need to include
errno.h or compilation fails:

../egg/egg-libgcrypt.c:54:1: error: 'ENOMEM' undeclared (first use in
this function)